#title in header
title: "Bonjour."

#main info
#owner
owner: "I'm cscnk52"
email: cscnk52@outlook.com
info: "A Student from China"
#description
desc: ""

#menu
menu:
#  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
#usercss: css/user.css

# social profile at the footer/bottom
footer: true
github: https://github.com/cscnk52/
douban: https://www.douban.com/people/csnck52/
rss: https://adisaktijrs.github.io/minima/

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io